version: "3.9"
services:
  web:
    build: .
    ports:
      - "5432:5432"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "postgres"
      ACCEPT_EULA: "Y"
